name = "cf-workers-audit-logs"
workers_dev = true
type = "javascript"
compatibility_date = "2022-05-23"

[triggers]
crons = ["* * * * *"]

# uncomment if you are deploying manually
kv_namespaces = [{binding="KV_AUDIT_LOGS", id="f9c2cf84d75c4eba92797e4125a5797b"}]
